version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestCorruptFlowProject
  gitServerName: gitHubIBM
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.testcorruptflow.integrations:e1
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: com.dachser:readFileList
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: pub.string:substring
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.string:length
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: com.dachser:getFile
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: com.dachser:invokeWebservice
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: com.dachser:processException
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: com.dachser:moveFile
  packages:
  - name: TestCorruptFlowProject
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
